### ISSUE TITLE
download links?

### ISSUE THREAD

**Issue by szechp** [Omico/CurrentActivity#10]
i can only find links to apks for version 3.0.4, where can i find the newer ones or do i have to build them myself?

**Comment by Omico** [comment]
> do i have to build them myself?
For now, yes!
I will create a CI/CD for this later.

**Comment by szechp** [comment]
i dont know if you've seen this: https://github.com/Omico/CurrentActivity/compare/main...488315:CurrentActivity_actions:main

this guy already did that, but didn't create a merge request for it lol. i downloaded the artifact from the latest pipeline and it works just fine.

**Comment by Omico** [comment]
Closed by https://github.com/Omico/CurrentActivity/commit/cf6ecfa7e98f609a6f4787992bb4aa1140900abd
