### ISSUE TITLE
FloatView code review

### ISSUE THREAD

**Issue by drakeet** [Omico/CurrentActivity#2]
应你的来信，帮忙简单看了下你的 `FloatView`，从代码看来，发现了一些问题：

- https://github.com/Omico/CurrentActivity/blob/master/library/src/main/java/me/omico/widget/FloatView.java#L63
https://github.com/Omico/CurrentActivity/blob/master/library/src/main/java/me/omico/widget/FloatView.java#L67
不需要检测 `View.getVisibility()`，如果你查看 `setVisibility` 源码就会发现检测其 Visibility 是多余的，setVisibility 内部会自行进行检测。

- https://github.com/Omico/CurrentActivity/blob/master/library/src/main/java/me/omico/widget/FloatView.java#L54
该方法取名叫 `add`，但却不接受参数，不太合适。这使得你的 `FloatView` 定位十分奇怪，`FloatView` 继承了 `View`，但却更像是一个 helper 角色。同样问题的还有 `remove` 方法。

- https://github.com/Omico/CurrentActivity/blob/master/library/src/main/java/me/omico/widget/FloatView.java#L39
`setOnFloatViewLongClickListener` 这个方法中，不需要对 `null` 进行特殊设置和对待。另外，也不需要在 listener 外再包一个 listener，我没看出你这样做的意义，除非你要在用户 listener 调用的同时做一些其他事情，但显然你没有这个需求，你的 listener wrapper 只做了调用用户 listener. 另外，`held` 参数也是冗余和容易让人产生混淆、迟疑的。

- 没看出你的 `FloatView` 为何要继承 `View`.

**Comment by drakeet** [comment]
而且像你这么检测是有漏洞问题的：
```java
if (mView.getVisibility() == View.GONE) mView.setVisibility(View.VISIBLE);
```
当 `mView` 被外界设置为 `INVISIBLE` 时，你的 `show` 方法将无法将之 `show` 出来。

**Comment by Omico** [comment]
我打算把FloatView做一个单独而且能够通用的控件，所以想继承View 目前还没构思这部分代码，所以。。。

**Comment by DrkCore** [comment]
- 将类名修改成 FloatWindow 并取消继承自View
- 将 add() 方法名改成 attach()

**Comment by Omico** [comment]
好吧，看来是我思路有些问题，总在 `View` 上纠结

**Comment by Omico** [comment]
已经提交，能再看看么https://github.com/Omico/CurrentActivity/commit/55354ce00aa0b5be072b12c47cd169ef7899cf82
@drakeet @DrkCore
