### ISSUE TITLE
Add Shizuku Support

### ISSUE THREAD

**Issue by thetoolz** [Omico/CurrentActivity#6]
Shizuku
Let your app use system APIs directly
https://shizuku.rikka.app/
https://github.com/RikkaApps/Shizuku

Use system APIs elegantly
Forget about root shell, you can use APIs with higher privileges "directly". Also, Shizuku is significantly faster than shell.

Support adb usage
If your "root required app" only needs adb permission, you can easily expand the audience by using Shizuku.

use Shizuku to avoid using Accessibility Service.

Apps using Shizuku
https://shizuku.rikka.app/apps.html

Developer guide
https://github.com/RikkaApps/Shizuku/blob/master/README.md

**Comment by Omico** [comment]
Hi @thetoolz, this is a great idea. Actually, I already decided to refactor the whole project and migrate to Shizuku at the end of last year. For now, I am just working on some secret projects. So, please wait. I will do that later.

**Comment by thetoolz** [comment]
Thanks for letting me know ☺️

**Comment by thetoolz** [comment]
useful for Fire tv since update 6.2.7.3
Accessibility Services Stopped working

**Comment by Omico** [comment]
> useful for Fire tv since update 6.2.7.3
> Accessibility Services Stopped working

Please, provide some log that can help me debug.
Otherwise, I think maybe Frie TV has changed some android framework APIs that can cause the problem.

**Comment by Omico** [comment]
Hello @thetoolz, I have rewritten the entire project and add Shizuku support. You can try it now.
