### ISSUE TITLE
拉不到库

### ISSUE THREAD

**Issue by fansangg** [Omico/CurrentActivity#7]
implementation 'me.omico:device:1.0.3'
    implementation 'me.omico:provider:1.0.3'
    implementation 'me.omico:utils:1.0.4'

这几个库现在拉不到了，3.x分支跑不起来啊

**Comment by Omico** [comment]
3.x 分支仅作为留档，不再维护了。

**Comment by fansangg** [comment]
> 

但是master看着功能不完善？

**Comment by Omico** [comment]
@fansangg 这个 app 是我初学 Android 时候的第一个项目，3.x 存在大量奇怪、不符合规范的实现，是我的黑历史留档。或能还能用，但已不建议继续使用。main 分支除了 ui 不完善外，核心功能是完整的。

**Comment by Omico** [comment]
我自己打开项目发现由于 Shizuku 版本过旧已经失效，近期将会重写。

**Comment by fansangg** [comment]
> 我自己打开项目发现由于 Shizuku 版本过旧已经失效，近期将会重写。

最近在维护一个老项目，需要查看当前activity然后找到你的这个库，想把长按和点击的事件加一个空事件的选项，没想到拉下来跑不了😅

**Comment by Omico** [comment]
> > 我自己打开项目发现由于 Shizuku 版本过旧已经失效，近期将会重写。
> 
> 最近在维护一个老项目，需要查看当前activity然后找到你的这个库，想把长按和点击的事件加一个空事件的选项，没想到拉下来跑不了😅

那非常简单，建议运行以下命令：
```shell
adb shell
watch dumpsys activity activities | grep mActivityComponent
```
